# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a87a77c77982dc99cc879897698db5b11be40cbee7b9b3bb004f7f7be05419c0dd6e7d18f681547ca2e7b1782726dd4e74a4a84208d5b0266051104088eef6a6

test:
  secret_key_base: 7fd158a14d533b92a74788a80ab84acc6618ae822e5f694abf0f525847af45a4dce08e161e48ea7973004edb161e9298c3f0f69d4f28769ddff3801cb0b8a0ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
